[package]
name = "comptu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = { version = "0.19.3", features = ["spirv"] }
tokio = "1.36.0"
